container:
  image: golang:latest

task:
  name: Test

  script: go test -v ./...

task:
  name: Release (Dry Run)
  only_if: $CIRRUS_TAG == ''
  depends_on:
    - Lint
    - Test
  install_script:
    - echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | tee /etc/apt/sources.list.d/goreleaser.list
    - apt-get update
    - apt-get -y install goreleaser-pro
  release_script: goreleaser build --snapshot
  goreleaser_artifacts:
    path: "dist/**"

task:
  name: Release
  only_if: $CIRRUS_TAG != ''
  depends_on:
    - Lint
    - Test
  env:
    GITHUB_TOKEN: ENCRYPTED[!98ace8259c6024da912c14d5a3c5c6aac186890a8d4819fad78f3e0c41a4e0cd3a2537dd6e91493952fb056fa434be7c!]
    FURY_TOKEN: ENCRYPTED[!97fe4497d9aca60a3d64904883b81e21f19706c6aedda625c97f62f67ec46b8efa74c55699956158bbf0a23726e7d9f6!]
    GORELEASER_KEY: ENCRYPTED[!9b80b6ef684ceaf40edd4c7af93014ee156c8aba7e6e5795f41c482729887b5c31f36b651491d790f1f668670888d9fd!]
  install_script:
    - echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | tee /etc/apt/sources.list.d/goreleaser.list
    - apt-get update
    - apt-get -y install goreleaser-pro
  release_script: goreleaser
