ec2_task:
  aws_credentials:
    role_arn: arn:aws:iam::471777771536:role/CirrusCIOIDC-Role-3eVDOPFmXTk0
    role_session_name: cirrus
    region: us-east-2
  ec2_instance:
    image: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-arm64-server-*
    architecture: arm64
    region: us-east-2
    type: a1.metal
  script: sleep 10
