project_name: vetu

before:
  hooks:
    - go mod download

builds:
  - main: cmd/vetu/main.go
    ldflags: >
      -X github.com/cirruslabs/vetu/internal/version.Version={{.Version}}
      -X github.com/cirruslabs/vetu/internal/version.Commit={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: binary
    format: binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
  - id: regular
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

release:
  prerelease: auto

nfpms:
  - package_name: vetu
    vendor: Cirrus Labs, Inc.
    homepage: https://github.com/cirruslabs/vetu
    maintainer: support@cirruslabs.org
    description: CLI for executing Cirrus tasks locally and in any CI
    section: misc
    scripts:
      postinstall: "scripts/postinstall.sh"
    dependencies:
      - cloud-hypervisor
      - edk2-cloud-hypervisor
    formats:
      - deb
      - rpm

furies:
  - account: cirruslabs
